apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.initSecretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  hub.services.grader.apiToken: {{ default "" .Values.apiToken | b64enc | quote }}
